name: e2e

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a35 # v5.3.0
        with:
          go-version: '1.25'

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@7b1c304e07aa482c27d74f35cf21a9a83eb5a2f5 # master
        with:
          toolchain: 1.93.0

      - name: Install stellar-cli
        run: cargo install --version 28.0.0 stellar-cli --locked

      - name: Run e2e tests
        env:
          SOROAUTH_RPC_URL: https://soroban-testnet.stellar.org
        run: |
          cd e2e/contracts && stellar contract build
          cd ../.. && go test -tags e2e -v ./e2e/...
